### PR TITLE
Adding CHANGELOG.md

### PR DESCRIPTION
**Pull request by ineiti**
Updated CHANGELOG.md

### CODE REVIEW

**Comment by PascalinDe** [comment]
good for this PR, can you investigate the failing tests though?

**Review by PascalinDe — APPROVED** [review]

**Comment by ineiti** [comment]
> good for this PR, can you investigate the failing tests though?

Vetting was failing, because it hasn't been run on the previous `main`. Disadvantage of `force push to main` :)

As it was just two lines in one file, I added it directly to this commit. Seemed to be a bit of overkill to do a separate PR. But will do if you think it's nicer.

**Comment by PascalinDe** [comment]
> > good for this PR, can you investigate the failing tests though?
> 
> Vetting was failing, because it hasn't been run on the previous `main`. Disadvantage of `force push to main` :)
> 
> As it was just two lines in one file, I added it directly to this commit. Seemed to be a bit of overkill to do a separate PR. But will do if you think it's nicer.

nah, fine for me like this

although now SonarCloud is unhappy...

**Comment by ineiti** [comment]
> although now SonarCloud is unhappy...

Ah, yes, this is because we commented it out, as we don't have a `SONARCLOUD_TOKEN`...

**Comment by ineiti** [comment]
And the tests are failing, even for the latest master of dela... Great! I'll put this in draft mode for the moment.

**Pull request merged**
